#!/usr/bin/env python3
"""rac-dashboard — tier-aware live Sigmond RAC services page + history, on gw2.

A background thread polls the frps admin API every 30s and records each client's
connection *sessions* (connect -> disconnect) in a small SQLite DB. The web view
(per request) shows a table sorted by name with a Status column (active / last
seen), plus a per-client history sub-page (?h=<name>).

Tier-aware: the WireGuard address the request arrived on selects the view
(10.112.0.2 mesh = full, 10.111.220.1 wd-rac = shareable services only); any
non-WireGuard interface is refused.
"""
import base64
import html
import json
import os
import sqlite3
import threading
import time
import urllib.request
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import urlparse, parse_qs

# --------------------------------------------------------------------------- config
# The SAME server.py runs on every gateway (gw2/WsprDaemon and the segregated
# HamSCI server). Per-gateway differences live in an optional JSON file next to
# this script, dashboard.conf; any key it omits falls back to the gw2 defaults
# below, so gw2 itself needs no config file. The two gateways never talk to each
# other — an admin laptop with both WireGuard tunnels is the only bridge.
_CFG_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'dashboard.conf')


def _load_cfg():
    try:
        with open(_CFG_PATH) as fh:
            return json.load(fh)
    except Exception:
        return {}


CFG = _load_cfg()

# Both frps instances on gw2: the secure gateway (:35736, API :7501) and the
# legacy open gateway (:35735, API :7500). Legacy clients get a ' [legacy]' name
# tag so a station that exists in both worlds (old autossh-era client + new
# appliance under the same callsign) keeps two distinct rows and histories.
# Polling the open server also lets the history DB accumulate an ever-seen
# record of legacy stations, which frps itself forgets on every restart.
# A single-tier gateway (HamSCI) lists just its one open frps here.
FRPS_APIS = [tuple(x) for x in CFG.get('frps_apis', [
    ('secure', 'http://127.0.0.1:7501/api/proxy/tcp', 'admin:admin'),
    ('legacy', 'http://127.0.0.1:7500/api/proxy/tcp', 'admin:admin'),
])]
PORT       = CFG.get('port', 50080)
# WireGuard admin networks -> view tier. mesh = full view, rac = shareable
# services only; a request arriving on any other interface is refused. gw2:
# mesh 10.112.0.2 + wd-rac 10.111.220.1. HamSCI overrides to its single VPN
# address as the full-view 'mesh' tier.
ADMIN_NETS = CFG.get('admin_nets', {'10.112.0.2': 'mesh', '10.111.220.1': 'rac',
                                    '10.111.221.1': 'sonde'})
# Gateway address most sonde users actually have: the /sondes page on the
# admin tiers renders its ssh links with this (typical sonde users hold
# wd-rac WireGuard configs, so they reach gw2 at 10.111.220.1 — an admin's
# own arrival address would be wrong in shared instructions). The wd-sonde
# watcher tier still gets its own arrival address, the only one its
# firewall rules allow.
SONDE_USER_GW = CFG.get('sonde_user_gw', '10.111.220.1')
# Gateway VPN addresses a viewer's browser might be able to reach, in
# preference order: the admins' wd-mesh address first, then the shareable
# wd-rac address. The page probes each (GET /ping on this same dashboard
# port) from the browser and rewrites its ssh/web links to the first one
# that answers, so every viewer sees commands that work for THEIR tunnel;
# the server-rendered default (the arrival address) is the no-JS fallback.
GW_CANDIDATES = [tuple(x) for x in CFG.get('gateway_addrs', [
    ('10.112.0.2', 'wd-mesh'), ('10.111.220.1', 'wd-rac')])]
# SSH login account served to tooling (ssr.sh) when a station's frps metadata
# carries no explicit user. gw2/WsprDaemon -> wduser; HamSCI -> wsprdaemon.
DEFAULT_ACCOUNT = CFG.get('default_account', 'wduser')
# Which gateway/network this dashboard fronts (surfaced in /api for the client).
GATEWAY    = CFG.get('gateway', 'wsprdaemon')
# Human-facing brand in the page heading/title (HamSCI mirror sets 'HamSCI').
TITLE      = CFG.get('title', 'Sigmond')
# Optional per-RAC credentials map (JSON: {"<rac>": {"account","password",
# "port_fwd"}}) next to this script, generated by the admin from ssr.conf. The
# real login account is served on every tier (a login name is not a secret);
# the stored password and port-forwards are served ONLY on the full-trust mesh
# tier, so the shareable/rac tier never sees them. Lets ssr auto-login without
# the admin's encrypted conf.
CREDS_FILE = CFG.get('creds_file',
                     os.path.join(os.path.dirname(os.path.abspath(__file__)), 'rac-creds.json'))
DB_PATH    = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'rac-history.db')
POLL_SEC   = 30
RETAIN_SEC = 180 * 86400          # prune closed sessions older than ~6 months

# Shared encrypted ssr conf blobs, served verbatim at GET /conf?f=<name>
# (mesh tier ONLY). These are openssl-encrypted by the admin's passphrase —
# the gateway serves ciphertext; decryption happens on the admin's machine.
CONF_DIR = CFG.get('conf_dir', '/home/wsprdaemon/rac-conf')
CONF_WHITELIST = tuple(CFG.get('conf_whitelist',
                               ('rac-master.conf.enc', 'rac-hamsci-master.conf.enc')))

SUFFIXES = [
    ('-host-ssh', 'ssh', 'ssh',   'mesh-only', 'host SSH'),
    ('-sonde-ssh', 'ssh', 'ssh',  'sonde',     'Sonde SSH'),  # Wsprsonde host
    ('-host-ui',  'web', 'https', 'mesh-only', 'Proxmox UI'),
    ('-vm-ssh',   'ssh', 'ssh',   'mesh-only', 'VM SSH'),
    ('-vm-web',   'web', 'http',  'shareable', 'VM ka9q-web'),
    ('-vm-grape', 'web', 'http',  'shareable', 'GRAPE charts'),  # WD 3.4.6+ carrier strip charts, 40800+rac
    ('-ssh',      'ssh', 'ssh',   'mesh-only', 'SSH'),        # receiver (smd)
    ('-web',      'web', 'http',  'shareable', 'ka9q-web'),   # receiver (smd)
]
COLUMNS = [
    ('VM Web',          ['VM ka9q-web', 'ka9q-web'], 'web'),
    ('GRAPE charts',    ['GRAPE charts'],            'web'),
    ('VM SSH',          ['VM SSH', 'SSH'],           'ssh'),
    ('Proxmox UI',      ['Proxmox UI'],              'web'),
    ('Proxmox box SSH', ['host SSH'],                'ssh'),
    ('Sonde SSH',       ['Sonde SSH'],               'ssh'),
]


def svc_visible(svc, tier):
    """Tier filter for one service. mesh sees everything; the sonde tier
    (wd-sonde WireGuard users) sees ONLY Wsprsonde services; the rac tier
    sees everything not marked mesh-only."""
    if tier == 'mesh':
        return True
    if tier == 'sonde':
        return svc['tier'] == 'sonde'
    return svc['tier'] != 'mesh-only'

STYLE = (
    'body{font-family:system-ui,-apple-system,sans-serif;max-width:1000px;'
    'margin:2rem auto;padding:0 1rem;color:#222}h1{font-size:1.4rem;margin-bottom:.2rem}'
    '.sub{color:#777;font-size:.85rem;margin-bottom:1rem}'
    'table{border-collapse:collapse;width:100%;font-size:.92rem}'
    'th,td{text-align:left;padding:.35rem .8rem;border-bottom:1px solid #ececec;white-space:nowrap}'
    'th{font-size:.74rem;text-transform:uppercase;letter-spacing:.04em;color:#999;'
    'border-bottom:2px solid #ddd}th.svc,td.svc{text-align:center}'
    'td.name{font-family:ui-monospace,Menlo,monospace;font-weight:600}'
    'a{color:#1a6dd6;text-decoration:none}a:hover{text-decoration:underline}'
    'code{background:#f4f4f4;padding:.1rem .35rem;border-radius:4px;font-size:.82rem;color:#555}'
    '.dot{color:#ccc}.on{color:#28a745;font-weight:600}.off-row td{opacity:.5}'
    '.ago{color:#999;font-size:.85rem}tr:hover td{background:#fafafa}'
    '.act{text-decoration:underline;cursor:pointer}')

# Clipboard copy that works over plain HTTP (navigator.clipboard needs HTTPS):
# a transient textarea + execCommand, with a brief "copied" confirmation.
SCRIPT = ("<script>function cp(el,t){var a=document.createElement('textarea');"
          "a.value=t;a.style.position='fixed';a.style.opacity=0;"
          "document.body.appendChild(a);a.focus();a.select();"
          "try{document.execCommand('copy');}catch(e){}document.body.removeChild(a);"
          "var o=el.textContent;el.textContent='copied';"
          "setTimeout(function(){el.textContent=o;},900);}"
          "function sshcmd(el){return 'ssh -p '+el.dataset.port+' '"
          "+el.dataset.user+'@'+window.GW;}</script>")

# Client-side VPN detection (admin tiers only): probe each candidate
# gateway address via GET /ping and rewrite the ssh/web links to the first
# reachable one. %DEFAULT%/%CANDS%/%PORT% filled in by render_main.
PROBE_SCRIPT = """<script>
(function(){
 var cands=%CANDS%,done=false;
 function apply(ip,label){
  window.GW=ip;
  document.querySelectorAll('a.ssh').forEach(function(a){a.title=sshcmd(a);});
  document.querySelectorAll('a.web').forEach(function(a){
   a.href=a.dataset.proto+'://'+ip+':'+a.dataset.port+'/';});
  var n=document.getElementById('gwnote');
  if(n){n.textContent='ssh links via your '+label+' VPN ('+ip+')';}
 }
 function trial(i){
  if(i>=cands.length||done)return;
  var c=new AbortController(),t=setTimeout(function(){c.abort();},1500);
  fetch('http://'+cands[i][0]+':%PORT%/ping',{signal:c.signal,cache:'no-store'})
   .then(function(r){clearTimeout(t);
    if(!done&&r.ok){done=true;apply(cands[i][0],cands[i][1]);}else{trial(i+1);}})
   .catch(function(){clearTimeout(t);trial(i+1);});
 }
 trial(0);
})();
</script>"""


# --------------------------------------------------------------------------- DB
def db():
    con = sqlite3.connect(DB_PATH, timeout=5)
    con.execute('PRAGMA journal_mode=WAL')
    return con


def init_db():
    con = db()
    con.execute('''CREATE TABLE IF NOT EXISTS sessions(
        id INTEGER PRIMARY KEY,
        name TEXT NOT NULL,
        connected_at INTEGER NOT NULL,
        last_seen INTEGER NOT NULL,
        disconnected_at INTEGER)''')
    con.execute('CREATE INDEX IF NOT EXISTS idx_sess_name ON sessions(name)')
    try:  # added later: remember each station's RAC number so OFFLINE
        con.execute('ALTER TABLE sessions ADD COLUMN rac INTEGER')
    except sqlite3.OperationalError:
        pass  # column already exists
    con.commit()
    con.close()


def record(online, now):
    """online: {client_name: rac_or_None}"""
    con = db()
    c = con.cursor()
    for name, rac in online.items():
        row = c.execute('SELECT id FROM sessions WHERE name=? AND disconnected_at IS NULL',
                        (name,)).fetchone()
        if row:
            c.execute('UPDATE sessions SET last_seen=?, rac=COALESCE(?,rac) WHERE id=?',
                      (now, rac, row[0]))
        else:
            c.execute('INSERT INTO sessions(name,connected_at,last_seen,rac) VALUES(?,?,?,?)',
                      (name, now, now, rac))
    for sid, name, last_seen in c.execute(
            'SELECT id,name,last_seen FROM sessions WHERE disconnected_at IS NULL').fetchall():
        if name not in online:
            c.execute('UPDATE sessions SET disconnected_at=? WHERE id=?', (last_seen, sid))
    c.execute('DELETE FROM sessions WHERE disconnected_at IS NOT NULL AND disconnected_at<?',
              (now - RETAIN_SEC,))
    con.commit()
    con.close()


def migrated_legacy(names, rac_for):
    """The ' [legacy]' rows that a non-legacy row supersedes: same base name,
    or same RAC number. A station upgraded from the open tier to the secure
    tier keeps its open-tier history (GET /?h=NAME) but is listed once, as the
    live secure entry, instead of once active and once 'legacy, offline'."""
    plain = {n for n in names if not n.endswith(' [legacy]')}
    racs = {rac_for(n) for n in plain} - {None}
    hidden = set()
    for n in names:
        if not n.endswith(' [legacy]'):
            continue
        base = n[:-len(' [legacy]')]
        if base in plain or rac_for(n) in racs:
            hidden.add(n)
    return hidden


def status_map():
    con = db()
    rows = con.execute('''SELECT name,
        MAX(disconnected_at IS NULL) AS active,
        MAX(last_seen) AS last_seen,
        MIN(connected_at) AS first_seen,
        COUNT(*) AS sessions,
        MAX(rac) AS rac
        FROM sessions GROUP BY name''').fetchall()
    con.close()
    return {r[0]: {'active': bool(r[1]), 'last_seen': r[2],
                   'first_seen': r[3], 'sessions': r[4], 'rac': r[5]} for r in rows}


def history(name):
    con = db()
    rows = con.execute('''SELECT connected_at,disconnected_at,last_seen FROM sessions
        WHERE name=? ORDER BY connected_at DESC LIMIT 500''', (name,)).fetchall()
    con.close()
    return rows


# ----------------------------------------------------------------------- poller
def fetch_proxies():
    out = []
    for src, url, auth in FRPS_APIS:
        try:
            req = urllib.request.Request(url)
            req.add_header('Authorization',
                           'Basic ' + base64.b64encode(auth.encode()).decode())
            with urllib.request.urlopen(req, timeout=8) as r:
                for p in json.load(r).get('proxies') or []:
                    p['_src'] = src
                    out.append(p)
        except Exception:
            pass  # one instance being down must not blank the whole page
    return out


def strip_hash(name):
    if '.' in name:
        head, rest = name.split('.', 1)
        if len(head) == 16 and all(c in '0123456789abcdef' for c in head):
            return rest
    return name


def parse(name):
    for suf, kind, proto, tier, label in SUFFIXES:
        if name.endswith(suf):
            return name[:-len(suf)], kind, proto, tier, label
    if name.endswith('-WEB'):
        client = name[:-4]
        if 'PROXMOX' in client.upper():
            return client, 'web', 'https', 'mesh-only', 'Proxmox UI'
        return client, 'web', 'http', 'shareable', 'ka9q-web'
    return name, 'ssh', 'ssh', 'mesh-only', 'SSH'


def rac_of(svcs):
    """Derive the RAC number from any of a client's ports — every band
    (35800 ssh/vm-ssh, 45800 web/vm-web, 50800 host-ssh, 55800 host-ui)
    is base + rac."""
    for s in svcs.values():
        p = s.get('port')
        if isinstance(p, int):
            if 37800 <= p <= 37899:      # Wsprsonde band: ID 2000-2099
                return p - 35800
            for base in (35800, 40800, 45800, 50800, 55800):
                if base <= p <= base + 999:
                    return p - base
    return None


def is_sonde(rac):
    return rac is not None and 2000 <= rac <= 2099


def load_creds():
    """Admin-supplied per-RAC credentials map, re-read each request so the
    admin can refresh it without restarting. {} if absent/unreadable."""
    try:
        with open(CREDS_FILE) as fh:
            return json.load(fh)
    except Exception:
        return {}


def account_and_ssh_port(svcs, rac):
    """Login account + primary SSH port for a station, for tooling (ssr.sh).

    account:  an explicit frps-metadata user on any of the station's SSH
              services if present, else this gateway's DEFAULT_ACCOUNT.
    ssh_port: the receiver/VM SSH port (the 35800+rac band) when live, else
              the deterministic 35800+rac. Reaching it still requires the
              admin WireGuard tier plus a valid SSH key — the port formula
              itself is not a secret."""
    account = None
    ssh_port = None
    for s in svcs.values():
        if s.get('kind') != 'ssh':
            continue
        if account is None and s.get('user'):
            account = s['user']       # reported by the frpc client (metadatas.user)
        p = s.get('port')
        if ssh_port is None and isinstance(p, int) and (
                35800 <= p <= 36799 or 37800 <= p <= 37899):
            ssh_port = p
    if ssh_port is None and rac is not None:
        ssh_port = 35800 + rac
    ### from_meta: True when the station itself reported its login account, so
    ### callers can let it win over the admin's rac-creds table.
    from_meta = account is not None
    return (account or DEFAULT_ACCOUNT), ssh_port, from_meta


def live_services():
    """{client: {label: svc}} for currently-online proxies, + {client: rac}."""
    clients = {}
    for p in fetch_proxies():
        name = strip_hash(p.get('name', ''))
        if not name or p.get('status') != 'online':
            continue
        client, kind, proto, tier, label = parse(name)
        if p.get('_src') == 'legacy':
            client += ' [legacy]'
        conf = p.get('conf') or {}
        # frp v0.64 (gw2) uses camelCase remotePort/metadatas; older frp
        # v0.3x (HamSCI) uses snake_case remote_port/meta_datas — accept both.
        port = conf.get('remotePort')
        if port is None:
            port = conf.get('remote_port')
        meta = conf.get('metadatas') or conf.get('meta_datas') or {}
        clients.setdefault(client, {})[label] = {
            'kind': kind, 'proto': proto, 'tier': tier, 'label': label,
            'port': port,
            'user': meta.get('user') if isinstance(meta, dict) else None}
    online = {c: rac_of(svcs) for c, svcs in clients.items()}
    return clients, online


def poller():
    while True:
        try:
            _clients, online = live_services()
            record(online, int(time.time()))
        except Exception:
            pass
        time.sleep(POLL_SEC)


# ------------------------------------------------------------------ formatting
def ago(ts, now):
    d = max(0, now - ts)
    if d < 60:
        return f'{d}s ago'
    if d < 3600:
        return f'{d // 60}m ago'
    if d < 86400:
        return f'{d // 3600}h ago'
    return f'{d // 86400}d ago'


def utc(ts):
    return time.strftime('%Y-%m-%d %H:%M', time.gmtime(ts)) + 'Z'


def dur(a, b):
    s = max(0, b - a)
    if s < 3600:
        return f'{s // 60}m'
    if s < 86400:
        return f'{s // 3600}h {s % 3600 // 60}m'
    return f'{s // 86400}d {s % 86400 // 3600}h'


# --------------------------------------------------------------------- rendering
def page(title, body):
    return ('<!doctype html><html><head><meta charset="utf-8">'
            '<title>' + html.escape(title) + '</title>'
            '<meta http-equiv="refresh" content="30">'
            '<style>' + STYLE + '</style>' + SCRIPT +
            '</head><body>' + body + '</body></html>')


def render_main(gw_ip, tier, sort='name', desc=False, only_sonde=False):
    now = int(time.time())
    clients, _online = live_services()
    stat = status_map()
    creds = load_creds() if tier == 'mesh' else {}   # passwords: mesh tier only
    # tier-filter live services
    vis = {}
    for name, svcs in clients.items():
        f = {lab: s for lab, s in svcs.items() if svc_visible(s, tier)}
        if f:
            vis[name] = f
    # Sonde-only station filter: forced for the wd-sonde tier (which must not
    # even see the names of non-sonde stations), optional for admin tiers via
    # GET /sondes.
    if tier == 'sonde' or only_sonde:
        only_sonde = True
        vis = {n: svcs for n, svcs in vis.items()
               if is_sonde(rac_of(svcs)) or is_sonde(stat.get(n, {}).get('rac'))}
        stat = {n: st for n, st in stat.items() if is_sonde(st.get('rac'))}
    present = [(h, ls, k) for (h, ls, k) in COLUMNS
               if any(any(l in vis[c] for l in ls) for c in vis)]

    def row_facts(name):
        rac = rac_of(vis.get(name, {})) if name in vis else None
        if rac is None:
            rac = stat.get(name, {}).get('rac')
        active = bool(stat.get(name, {}).get('active') or name in vis)
        ls = stat.get(name, {}).get('last_seen') or 0
        return rac, active, ls

    def sort_key(name):
        rac, active, ls = row_facts(name)
        if sort == 'rac':
            return (rac is None, rac if rac is not None else 0, name.lower())
        if sort == 'status':
            # active first, then most recently seen
            return (not active, -ls, name.lower())
        return (name.lower(),)
    names = sorted(set(stat) | set(vis), key=sort_key, reverse=desc)
    hidden = migrated_legacy(names, lambda n: row_facts(n)[0])
    names = [n for n in names if n not in hidden]

    heading = ' Wsprsonde status' if only_sonde else ' Remote Access Channel (RAC)'
    b = ['<h1>' + html.escape(TITLE) + heading + '</h1>']
    tl = {'mesh': 'full mesh view', 'sonde': 'wd-sonde view (Wsprsonde hosts only)'}.get(
        tier, 'wd-rac view (shareable services only)')
    # Admin tiers get a link between the full view and the sonde-only view;
    # the wd-sonde tier has nothing else to link to.
    nav = ''
    if tier != 'sonde':
        nav = (' &middot; <a href="/">all stations</a>' if only_sonde
               else ' &middot; <a href="/sondes">Wsprsondes only</a>')
    # Address used in the service links: the sonde-only admin view shows the
    # address typical sonde users have (see SONDE_USER_GW); everything else
    # uses the viewer's own arrival address.
    link_ip = SONDE_USER_GW if (only_sonde and tier != 'sonde') else gw_ip
    # Admin tiers carry a note that the probe script updates once it learns
    # which VPN this browser actually has (see PROBE_SCRIPT).
    ipnote = ('' if tier == 'sonde' else
              f' &middot; <span id="gwnote">ssh links use <code>{link_ip}</code></span>')
    nact = sum(1 for n in names if stat.get(n, {}).get('active') or n in vis)
    b.append(f'<div class="sub">via gw2 <code>{gw_ip}</code> &middot; {tl} &middot; '
             f'{nact} active / {len(names)} known{nav}{ipnote} &middot; auto-refresh 30s</div>')
    def th(col, label):
        # clicking the current sort column flips direction
        d = '&amp;d=1' if (sort == col and not desc) else ''
        arrow = (' &#9660;' if desc else ' &#9650;') if sort == col else ''
        return f'<th><a href="?s={col}{d}">{label}</a>{arrow}</th>'
    b.append('<table><tr>' + th('name', 'Name') + th('rac', 'RAC') + th('status', 'Status'))
    if tier == 'mesh':
        b.append('<th>Login</th>')
    for h, _ls, _k in present:
        b.append(f'<th class="svc">{h}</th>')
    b.append('</tr>')
    for name in names:
        rac, active, _lastseen = row_facts(name)
        ls = stat.get(name, {}).get('last_seen')
        rowcls = '' if active else ' class="off-row"'
        st = '<span class="on">&#9679; active</span>' if active else (
            f'<span class="ago">last seen {ago(ls, now)}</span>' if ls else '&mdash;')
        b.append(f'<tr{rowcls}><td class="name">'
                 f'<a href="?h={html.escape(name)}">{html.escape(name)}</a></td>'
                 f'<td class="name">{rac if rac is not None else "&mdash;"}</td>'
                 f'<td>{st}</td>')
        if tier == 'mesh':
            ### Login: real account + a click-to-copy password (password passed
            ### via a data- attribute, never inlined into the JS string).
            c = creds.get(str(rac)) if rac is not None else None
            acct = (c or {}).get('account') or ''
            pw = (c or {}).get('password') or ''
            if pw:
                cell = ('%s / <a class="act" href="#" data-pw="%s" '
                        'onclick="cp(this,this.dataset.pw);return false" '
                        'title="copy password">pw</a>'
                        % (html.escape(acct) or '&mdash;', html.escape(pw)))
            elif acct:
                cell = html.escape(acct)
            else:
                cell = '<span class="dot">&middot;</span>'
            b.append(f'<td>{cell}</td>')
        svcs = vis.get(name, {})
        for _h, labels, kind in present:
            svc = next((svcs[l] for l in labels if l in svcs), None)
            if not svc:
                b.append('<td class="svc"><span class="dot">&middot;</span></td>')
            elif kind == 'web':
                b.append('<td class="svc"><a class="act web" target="_blank" '
                         'data-proto="%s" data-port="%s" href="%s://%s:%s/">open</a></td>'
                         % (svc['proto'], svc['port'], svc['proto'], link_ip, svc['port']))
            else:
                default_user = 'wsprsonde' if svc['tier'] == 'sonde' else 'root'
                user = svc.get('user') or default_user
                cmd = 'ssh -p %s %s@%s' % (svc['port'], user, link_ip)
                b.append('<td class="svc"><a class="act ssh" href="#" title="%s" '
                         'data-port="%s" data-user="%s" '
                         'onclick="cp(this,sshcmd(this));return false">ssh</a></td>'
                         % (cmd, svc['port'], user))
        b.append('</tr>')
    b.append('</table>')
    # window.GW is what sshcmd()/cp() compose the command from; the probe
    # (admin tiers only) may then update it to the viewer's own VPN.
    b.insert(0, '<script>window.GW=%s</script>' % json.dumps(link_ip))
    if tier != 'sonde':
        b.append(PROBE_SCRIPT.replace('%CANDS%', json.dumps([list(c) for c in GW_CANDIDATES]))
                             .replace('%PORT%', str(PORT)))
    return page(TITLE + (' Wsprsondes' if only_sonde else ' RAC'), ''.join(b))


def render_api(tier):
    """Machine-readable view for tooling (ssr.sh etc.): every known station
    with its RAC number, live services (tier-filtered like the page), and
    status. GET /api"""
    now = int(time.time())
    clients, _online = live_services()
    stat = status_map()
    creds = load_creds()
    out = []

    def rac_for(name):
        r = rac_of(clients.get(name, {})) if name in clients else None
        return r if r is not None else stat.get(name, {}).get('rac')

    names = sorted(set(stat) | set(clients))
    hidden = migrated_legacy(names, rac_for)
    for name in names:
        if name in hidden:
            continue
        svcs = {lab: s for lab, s in clients.get(name, {}).items()
                if svc_visible(s, tier)}
        rac = rac_for(name)
        if tier == 'sonde' and not is_sonde(rac):
            continue
        account, ssh_port, from_meta = account_and_ssh_port(clients.get(name, {}), rac)
        ### Account precedence: what the frpc client itself reported
        ### (metadatas.user) wins; otherwise the admin's rac-creds table; else
        ### the gateway default. The table also supplies password + port_fwd
        ### (mesh tier only) regardless of where the account came from.
        c = creds.get(str(rac)) if rac is not None else None
        if not from_meta and c and c.get('account'):
            account = c['account']
        station = {
            'name': name,
            'rac': rac,
            'account': account,
            'ssh_port': ssh_port,
            'legacy': name.endswith(' [legacy]'),
            'active': bool(stat.get(name, {}).get('active') or name in clients),
            'last_seen': stat.get(name, {}).get('last_seen'),
            'services': {lab: {'port': s['port'], 'proto': s['proto'],
                               'kind': s['kind'], 'tier': s['tier']}
                         for lab, s in svcs.items()},
        }
        if c and tier == 'mesh':
            if c.get('password'):
                station['password'] = c['password']
            if c.get('port_fwd'):
                station['port_fwd'] = c['port_fwd']
        out.append(station)
    return json.dumps({'generated': now, 'tier': tier, 'gateway': GATEWAY,
                       'default_account': DEFAULT_ACCOUNT, 'stations': out},
                      indent=1) + '\n'


def render_history(name, gw_ip):
    now = int(time.time())
    rows = history(name)
    b = [f'<h1>{html.escape(name)} &mdash; connection history</h1>',
         '<div class="sub"><a href="/">&larr; all machines</a> &middot; '
         f'{len(rows)} session(s) &middot; via gw2 <code>{gw_ip}</code></div>']
    if not rows:
        b.append('<p>No history recorded yet.</p>')
        return page(name + ' history', ''.join(b))
    b.append('<table><tr><th>Connected</th><th>Disconnected</th><th>Duration</th></tr>')
    for connected_at, disconnected_at, last_seen in rows:
        if disconnected_at is None:
            end = '<span class="on">&#9679; active</span>'
            d = dur(connected_at, now)
        else:
            end = f'{utc(disconnected_at)} <span class="ago">({ago(disconnected_at, now)})</span>'
            d = dur(connected_at, disconnected_at)
        b.append(f'<tr><td>{utc(connected_at)}</td><td>{end}</td><td>{d}</td></tr>')
    b.append('</table>')
    return page(name + ' history', ''.join(b))


class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        local = self.connection.getsockname()[0]
        tier = ADMIN_NETS.get(local)
        if tier is None:
            self.send_response(403)
            self.end_headers()
            self.wfile.write(b'forbidden: WireGuard admin networks only')
            return
        try:
            u = urlparse(self.path)
            q = parse_qs(u.query)
            ctype = 'text/html; charset=utf-8'
            if u.path == '/ping':
                # reachability probe for the client-side VPN detection; CORS
                # header lets a page served from one gateway address probe
                # the others (all still gated by ADMIN_NETS above).
                self.send_response(204)
                self.send_header('Access-Control-Allow-Origin', '*')
                self.send_header('Cache-Control', 'no-store')
                self.end_headers()
                return
            if u.path == '/conf':
                # encrypted credential blobs: full-trust mesh tier only
                if tier != 'mesh':
                    self.send_response(403)
                    self.end_headers()
                    self.wfile.write(b'forbidden: mesh tier only')
                    return
                f = (q.get('f') or ['rac-master.conf.enc'])[0]
                if f not in CONF_WHITELIST:
                    self.send_response(404)
                    self.end_headers()
                    self.wfile.write(b'unknown conf')
                    return
                try:
                    with open(os.path.join(CONF_DIR, f), 'rb') as fh:
                        blob = fh.read()
                except OSError:
                    self.send_response(404)
                    self.end_headers()
                    self.wfile.write(b'conf not present on gateway')
                    return
                self.send_response(200)
                self.send_header('Content-Type', 'application/octet-stream')
                self.send_header('Content-Length', str(len(blob)))
                self.end_headers()
                self.wfile.write(blob)
                return
            if u.path == '/api':
                body = render_api(tier)
                ctype = 'application/json'
            elif 'h' in q and q['h']:
                # sonde tier: history only for stations in the sonde band
                if tier == 'sonde' and not is_sonde(
                        status_map().get(q['h'][0], {}).get('rac')):
                    self.send_response(404)
                    self.end_headers()
                    self.wfile.write(b'unknown station')
                    return
                body = render_history(q['h'][0], local)
            else:
                sort = (q.get('s') or ['name'])[0]
                if sort not in ('name', 'rac', 'status'):
                    sort = 'name'
                body = render_main(local, tier, sort, bool(q.get('d')),
                                   only_sonde=(u.path == '/sondes'))
            page_b = body.encode()
        except Exception as exc:
            self.send_response(502)
            self.end_headers()
            self.wfile.write(('error: %s' % exc).encode())
            return
        self.send_response(200)
        self.send_header('Content-Type', ctype)
        self.send_header('Content-Length', str(len(page_b)))
        self.end_headers()
        self.wfile.write(page_b)

    def log_message(self, *a):
        pass


if __name__ == '__main__':
    init_db()
    threading.Thread(target=poller, daemon=True).start()
    ThreadingHTTPServer(('0.0.0.0', PORT), Handler).serve_forever()
